---
title: Lecture 13 - Note
subtitle: Facets; Data Visualization Process; Geometric Objects
author: 
  - name: Byeong-Hak Choe
date: 2024-03-19

execute: 
  echo: true    # true false
  eval: true    # true false
  warning: false    # true false
  message: false    # true false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true    # true false
    number-sections: true    # true false
    code-fold: false    # true false show       # https://quarto.org/docs/output-formats/html-code.html
    code-tools: true    # true false
    highlight-style: a11y        # a11y arrow ayu atom-one breeze github gruvbox tango espresso
                                     # pygments tango espresso espresso zenburn kate nord
                                    # https://quarto.org/docs/output-formats/html-code.html#highlighting
---


```{r setup}
#| include: false
library(tidyverse)
library(hrbrthemes)
library(skimr)
library(DT)
library(rmarkdown)

```


# 



```{r}
ggplot(data = mpg) + 
  geom_histogram(mapping = 
                aes(x = displ),
                bins = 5)
```






```{r}
ggplot(data = mpg) + 
  geom_histogram(mapping = 
                aes(x = displ),
                binwidth = 1)
```



# Line Chart

```{r}
path <- 
  "https://bcdanl.github.io/data/NVDA.csv"
nvda <- read_csv(path)

ggplot(data = nvda) + 
  geom_line(mapping = 
                aes(x = Date, 
                    y = Close)) +
  geom_point(mapping = 
                aes(x = Date, 
                    y = Close),
             size = .5) +
  geom_smooth(mapping = 
                aes(x = Date, 
                    y = Close))
  
```



# Geometric Objects

```{r}
ggplot(data = mpg ) +
  geom_point(mapping = aes(x = displ,
                            y = hwy,
                            linetype = drv),
             alpha = .5) +
  geom_smooth(mapping = aes(x = displ,
                            y = hwy,
                            linetype = drv))
```


```{r}
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy,
                            color = drv),
              )
```


```{r}
ggplot(data = mpg) + 
  geom_point(mapping = 
               aes(x = displ, 
                   y = hwy),
             alpha = .3) +
  geom_smooth(mapping = 
                aes(x = displ, 
                    y = hwy)) +
  geom_smooth(mapping = 
                aes(x = displ, 
                    y = hwy), 
              method = lm, 
              color = 'red')
```






```{r}
ggplot(data = mpg,
       mapping = 
               aes(x = displ, 
                   y = hwy)) + 
  geom_point(alpha = .3) +
  geom_smooth() +
  geom_smooth(method = lm, 
              color = 'red')
```



```{r}
ggplot(data = mpg,
       mapping = 
               aes(x = displ, 
                   y = hwy)) + 
  geom_point(alpha = .5, mapping = aes(color = class)
             ) +
  geom_smooth() +
  geom_smooth(method = lm, 
              color = 'red')
```

```{r}
mpg <- ggplot2::mpg
```


```{r}
class_vec <- mpg$class
class_vec

```

```{r}
class_vec == "subcompact"

```



```{r}
df_subcompact <- filter(mpg, 
                        class == "subcompact")
```


```{r}
ggplot(data = mpg, 
       mapping = 
         aes(x = displ, 
             y = hwy)) + 
  geom_point(mapping = 
               aes(color = class), 
             alpha = .5) + 
  geom_smooth(data = df_subcompact, 
              se = TRUE) # se stands for standard error
```




```{r}

ggplot(data = mpg) + 
  geom_point(mapping = 
               aes(x = displ, 
                   y = hwy),
             alpha = .3) +
  geom_smooth(mapping = 
                aes(x = displ, 
                    y = hwy)) 
```


# Classwork 7

```{r}
ggplot(data = mpg, 
       mapping = aes(x = displ, y = hwy, 
                     color = drv)) +
  geom_point(alpha = .4) +
  geom_smooth(se = FALSE)
```


## Q1c

### (a)

```{r}
ggplot(data = mpg,
       mapping = aes(x = displ, y = hwy)) +
  geom_point(alpha = .3) +
  geom_smooth(se = F)
  
```

### (b)


```{r}
ggplot(data = mpg,
       mapping = aes(x = displ, y = hwy)) +
  geom_point(alpha = .3) +
  geom_smooth(se = F,
              mapping = aes(group = drv))
  
```



```{r}
# multiple data.frames
```

