---
title: Lecture 17 - Note
subtitle: Filtering Observations; Arrange Observations
author: Byeong-Hak Choe
institute: SUNY Geneseo
date: 2024-04-04
format: 
  html
    # toc: true
    # toc-depth: 2
    # toc-expand: true
    # toc-title: Contents
# code-fold: true
code-tools: true

execute:
  echo: true
  eval: true
  message: false
  warning: false
  fig-width: 9
  fig-height: 6
---
```{r}
#| include: false
library(tidyverse)
library(skimr)
library(broom)
library(hrbrthemes)

theme_set(theme_ipsum() +
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = element_text(size = rel(1.5) ),
                axis.title.y = element_text(size = rel(1.5) ))
          )

```


# `flights` data.frame
We need to install the `nycflights13` package

  - `install.packages("nycflights13")`


```{r}
library(nycflights13)
flights <- nycflights13::flights

??flights
airlines

unique(flights$origin)

unique(flights$dest)
unique(flights$year)

```


# Filter

```{r}
jan1 <- flights |> 
  filter(month == 1, day == 1)

unique(jan1$month)
unique(jan1$day)

```

```{r}
dec25 <- flights |> 
  filter(month == 12, day == 25)

nrow(dec25)
```


```{r}
#| eval: false
flights$month
```


```{r}
class(flights$month)
class(flights$month == 1) # logical
```


```{r}
#| eval: false
flights$month == 1
```


```{r}
dec25$month

12 == 1

dec25$month == 1

class(dec25$month == 1) # logical

```


## Logical Operators

```{r}
#| eval: false
(flights$month == 1) & (flights$day == 1)
(flights$month == 2) & (flights$day == 1)


(flights$month == 2) | (flights$day == 1)



(flights$month == 1)
!(flights$month == 1)
```


```{r}
df <- data.frame(
  num = c(8, 9, 10, 11),
  chr = c("A", "C", "B", "A"))

df
```


```{r}
df |> 
  filter(num > 8 & num < 11)
```

```{r}
df |> 
  filter(num > 8, num < 11)
```

```{r}
df |> 
  filter(num < 10,
         chr == "A")
```

```{r}
#| eval: false
df |> 
  filter(num < 10,
         chr = "A") # error
```

```{r}
df |> filter(num < 10 | 
                chr == "A")
```


```{r}
df1 <- flights |> 
  filter( !( arr_delay > 120 | 
              dep_delay > 120) )

nrow(df1)
```

```{r}
df2 <- flights |> 
  filter(arr_delay <= 120 & dep_delay <= 120)

nrow(df2) == nrow(df1)
```

## `%in%` operator for multiple `|` 

```{r}
q4 <- flights |> 
  filter(month == 10 |
           month == 11 |
           month == 12 )

unique(q4$month)

```

```{r}
q4_in <- flights |> 
  filter(month %in% c(10, 11, 12))

unique(q4_in$month)

```





```{r}
second_half <- flights |> 
  filter(month == 7 |
           month == 8 |
           month == 9 |
           month == 10 |
           month == 11 |
           month == 12 )

unique(second_half$month)

```



```{r}

vec <- 7:12
second_half_in <-  flights |> 
  filter(month %in% vec)

unique(second_half_in$month)

```



```{r}
NA > 5
NA + 5
NA / 2
NA == NA



```


### `is.na()`

```{r}
x <- NA
is.na(x)
```


```{r}
y <- "missing"
is.na(y)
```

```{r}
df <- data.frame(y = c(1, NA, 3))
df
```

```{r}

df |> 
  filter(y > 1)

```

```{r}
df |> 
  filter( is.na(y) )
```


```{r}
df |> 
  filter( is.na(y) | y > 1 )

```


# `distinct()`

```{r}
flights |> 
  distinct() # no duplicates
```


```{r}
flights |> 
  distinct(origin, dest)


```

```{r}
df <- data.frame(
  var_1 = c(1,1,3,4),
  var_2 = c(1,1,5,6)
)

df
```
```{r}
df |> 
  distinct()
```

```{r}
flights |> 
  distinct(origin, dest, 
           .keep_all = TRUE)
```




```{r}
df <- data.frame(
  var_1 = c(3,4,6,1),
  var_2 = c(1,1,7,6)
)

df
```


```{r}
df |> 
  arrange(var_1)
```


```{r}
df |> 
  arrange(desc(var_1))
```


```{r}
df |> 
  arrange(-var_1)
```



## Classwork 9 Q1b

```{r}
df <- flights |> 
  filter(is.na(dep_time))

nrow(df)
```

