---
title: Classwork 1
subtitle: Computer Basics
date: 2024-01-25
from: markdown+emoji
---


## Practice Problems
- Do the following tasks:
  1. Download the file `nbc_show.zip` from [Brightspace](https://mylearning.suny.edu/d2l/home/1234666).
  2. Extract the file `nbc_show.zip`.
  4. Copy the pathname of `nbc_show.csv` 
  5. Type the following on an R script:
  
```{r}
#| eval: false
pathname <- "PATHNAME_OF_nbc_show.csv"
```

- For example, in Byeong-Hak's computer, `/Users/bchoe/My Drive/suny-geneseo/teaching-materials/lecture-data/nbc_show.csv` is the pathname of `nbc_show.csv`.

  7. In your R script, locate your mouse cursor on any part of the line with `pathname` by clicking the line or using arrow keys.
  8. Hit **Ctrl + Enter** (Windows users) / **command + Enter** (Mac users) to run the line of code.
  6. Save an R script to Documents folder or a new directory for the course.
    - If you use a new directory for the course, I recommend you to use the name without any space. For example, do not use name like `DANL 200`. Instead, use `DANL200` for the working directory.
  
- Let Byeong-Hak know if you have issues with the tasks!


<br><br>

# Discussion

<font size = "5">Welcome to our Classwork 1 Discussion Board! 👋 </font>

This space is designed for you to engage with your classmates about the material covered in Classwork 1.

Whether you are looking to delve deeper into the content, share thoughts, or have questions about the content, this is the perfect place for you.


If you have any specific questions for Byeong-Hak (**@bcdanl**) or peer classmate (@GitHub-Username) regarding the Classwork 1 materials or need clarification on any points, don't hesitate to ask here. 

Let's collaborate and learn from each other!

